server:
  servlet:
    context-path: /telemetries-persister
  port: 8082
spring:
  application:
    name: telemetry-ingestion-persister
  devtools:
    restart:
      enabled: false
  profiles:
#    active: mongoRepositories
    active: mongoTemplate
  data:
    mongodb:
      uuid-representation: standard
      uri: "my_uri"
      connect-timeout: 10s
      socket-timeout: 5s
      min-connections-per-host: 5
      max-connections-per-host: 50
      max-wait-time: 120s
      heartbeat-frequency: 5s
mongo:
  pool:
    minSize: 5
    maxSize: 200
    maxConnectionIdleTime: 30000
    maxConnectionLifeTime: 300000
management:
  endpoints:
    web:
      exposure:
        include: "*"
kafka:
  consumer:
    telemetries-topic: iot-devices-data
    commands-topic: iot-devices-commands
    poll-timeout-ms: 100
    restart-timeout-ms: 10000
    executor-termination-timeout-ms: 5000
    properties:
      bootstrap.servers: localhost:9092
      group.id: telemetry-events
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
      auto.offset.reset: earliest
      enable.auto.commit: false
      max.poll.records: 10000
      max.poll.interval: 300000
      fetch.min.bytes: 256
      fetch.max.wait.ms: 5000
      value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
  producer:
    topic: dead-letter-telemetries-persists
    executor-termination-timeout-ms: 5000
    properties:
      bootstrap.servers: localhost:9092
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      schema.registry.url: http://localhost:8081
      acks: all
      linger.ms: 10
      batch.size: 32768
      compression.type: snappy
      retries: 3
      retry.backoff.ms: 100
      enable.idempotence: true
      request.timeout.ms: 15000
      delivery.timeout.ms: 30000
      client.id: dead-letter-persists-producer
      auto.register.schemas: false
persister:
  retries:
    max.attempts: 15
    wait.duration.ms: 3000
