name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
  packages: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github-device-connector
        token: ${{ secrets.GH_PACKAGES_TOKEN }}
        cache: maven
    - name: Build with Maven
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: mvn -B -e -U package --file pom.xml
    - name: Copy settings.xml to build context
      run: |
        mkdir -p ci
        cp ~/.m2/settings.xml ci/settings.xml
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.11.1
    - name: Docker Login
      uses: docker/login-action@v3.6.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/iot-telemetry-ingestion-service:${{ github.run_number }}
        build-args: |
          GITHUB_ACTOR=${{ github.actor }}
          GITHUB_TOKEN=${{ secrets.GH_PACKAGES_TOKEN }}

    - name: Checkout k8s manifests repo
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.DOCKER_USERNAME }}/Kubernetes-Manifests
        token: ${{ secrets.MANIFESTS_REPO_TOKEN }}
        path: Kubernetes-Manifests
    - name: Update image tag in kustomization.yaml
      run: |
        cd Kubernetes-Manifests/iot-telemetry-ingestion-persister/overlays/dev
        kustomize edit set image ${{ secrets.DOCKER_USERNAME }}/iot-telemetry-ingestion-service:${{ github.run_number }}
    - name: Commit and push manifest changes
      run: |
        cd Kubernetes-Manifests
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        if ! git diff --quiet; then
          git add .
          git commit -m "chore: update image tag to ${{ github.run_number }}"
          git push
        else
          echo "No changes to commit"
        fi
